env_files = [{ path = "./env/dev.env", profile = "development" }]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
env_files = ["./env/prod.env"]
workspace = false

[tasks.dev]
run_task = { name = ["watch", "tunnel", "start-mysql"], parallel = true }
workspace = false

[tasks.watch]
command = "cargo"
args = ["run"]
watch = { watch = ["./packages/"] }
workspace = false

[tasks.tunnel]
command = "lt"
args = ["--port", "${PORT}", "-s", "${LOCALTUNNEL_SUBDOMAIN}"]
workspace = false

[tasks.start-mysql]
script_runner = "@duckscript"
script = '''
cd ./packages/minipub
exec docker-compose up -d
'''
workspace = false

[tasks.migrate]
script_runner = "@duckscript"
script = '''
set_env DATABASE_URL ${DB_URL}/${DB_NAME}
exec sea-orm-cli migrate refresh
'''
workspace = false
